#spring:
#  data:
#    elasticsearch:
#      cluster-name: es-cluster1
#      cluster-nodes: localhost:9300 # 程序连接es的端口号是9300

server:
  port: 8080
  servlet:
    context-path: /

spring:
  elasticsearch:
    rest:
      uris: http://localhost:9200
      username: elastic
      password: xxxxxx
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_website?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: xxxxxx